import type {
  OrderDetail,
  OrderListItem,
  OrderStatus,
} from '@/src/types/orders/orders.types';

export const ordersCopy = {
  title: 'Danh sách đơn hàng',
  filter: 'Lọc',
  filterTitle: 'Lọc đơn hàng',
  filterAll: 'Tất cả',
  idLabel: 'ID:',
  createdAtLabel: 'Ngày tạo:',
  totalCostLabel: 'Tổng chi phí:',
  paidLabel: 'Đã thanh toán:',
  packageCountLabel: 'Số kiện hàng:',
  actions: 'Thao tác',
  deleteOrder: 'Xoá đơn',
  viewDetail: 'Xem chi tiết',
  payOrder: 'Thanh toán',
  cancelOrder: 'Huỷ đơn',
  emptyOrders: 'Chưa có đơn hàng nào',
  emptyFilteredOrders: 'Không có đơn phù hợp bộ lọc',
} as const;

export const orderDetailCopy = {
  screenTitle: 'Chi tiết đơn hàng',
  back: 'Quay lại',
  notFound: 'Không tìm thấy đơn hàng',
  supplierLabel: 'Nhà cung cấp:',
  productsTitle: 'Sản phẩm',
  optionsTitle: 'Tuỳ chọn',
  noteTitle: 'Ghi chú',
  costTitle: 'Chi phí',
  goodsAmount: 'Tiền hàng:',
  estimatedFee: 'Phí tạm tính:',
  deposit: 'Đặt cọc:',
  totalAmount: 'Tổng tiền:',
  remainingAmount: 'Còn lại:',
  unitPriceLabel: 'Đơn giá:',
  lineTotalLabel: 'Thành tiền:',
  insurance: 'Bảo hiểm',
  woodPacking: 'Đóng gỗ',
  enabled: 'Có',
  disabled: 'Không',
  payOrder: 'Thanh toán',
  cancelOrder: 'Huỷ đơn',
  paySuccess: 'Thanh toán thành công (mock)',
  cancelSuccess: 'Đã huỷ đơn hàng (mock)',
} as const;

export const orderStatusLabels: Record<OrderStatus, string> = {
  awaitingDeposit: 'Chờ đặt cọc',
  awaitingPayment: 'Chờ thanh toán',
  readyToShip: 'Sẵn sàng giao',
  processing: 'Đang xử lý',
};

/** Mock placed orders for the orders list tab. */
export const mockOrderListItems: OrderListItem[] = [
  {
    id: '12979',
    createdAt: '2026-06-15',
    totalCostVnd: 44_009,
    paidVnd: 0,
    packageCount: 1,
    status: 'awaitingDeposit',
    productName: 'Phấn phủ dạng bột Marshmallow Finish',
    productQuantity: 1,
  },
  {
    id: '12954',
    createdAt: '2026-06-12',
    totalCostVnd: 890_650,
    paidVnd: 267_195,
    packageCount: 2,
    status: 'awaitingPayment',
    productName: 'Tai nghe Bluetooth chống ồn',
    productQuantity: 1,
  },
  {
    id: '12890',
    createdAt: '2026-06-08',
    totalCostVnd: 248_200,
    paidVnd: 248_200,
    packageCount: 1,
    status: 'readyToShip',
    productName: 'Áo thun nam cotton basic',
    productQuantity: 2,
  },
  {
    id: '12811',
    createdAt: '2026-06-01',
    totalCostVnd: 1_207_500,
    paidVnd: 362_250,
    packageCount: 3,
    status: 'processing',
    productName: 'Máy xay sinh tố đa năng',
    productQuantity: 1,
  },
];

/** Full mock order detail payloads keyed by order id. */
export const mockOrderDetails: Record<string, OrderDetail> = {
  '12979': {
    id: '12979',
    createdAt: '2026-06-15',
    totalCostVnd: 44_009,
    paidVnd: 0,
    packageCount: 1,
    status: 'awaitingDeposit',
    productName: 'Phấn phủ dạng bột Marshmallow Finish',
    productQuantity: 1,
    supplierName: '全款旗舰店',
    note: '',
    insurance: false,
    woodPacking: false,
    products: [
      {
        id: 'op-1',
        name: 'Phấn phủ dạng bột Marshmallow Finish',
        variant: '颜色分类：【店主强推XL】加强遮瑕',
        priceCny: 6.26,
        quantity: 1,
      },
    ],
    costs: {
      goodsVnd: 22_849,
      estimatedFeeVnd: 12_500,
      depositVnd: 8_660,
      totalVnd: 44_009,
      paidVnd: 0,
      remainingVnd: 44_009,
    },
  },
  '12954': {
    id: '12954',
    createdAt: '2026-06-12',
    totalCostVnd: 890_650,
    paidVnd: 267_195,
    packageCount: 2,
    status: 'awaitingPayment',
    productName: 'Tai nghe Bluetooth chống ồn',
    productQuantity: 1,
    supplierName: 'AudioHub Official',
    note: 'Giao giờ hành chính',
    insurance: true,
    woodPacking: false,
    products: [
      {
        id: 'op-2',
        name: 'Tai nghe Bluetooth chống ồn',
        variant: 'Màu: Đen | Bảo hành 12 tháng',
        priceCny: 244,
        quantity: 1,
      },
    ],
    costs: {
      goodsVnd: 890_600,
      estimatedFeeVnd: 0,
      depositVnd: 267_195,
      totalVnd: 890_650,
      paidVnd: 267_195,
      remainingVnd: 623_455,
    },
  },
  '12890': {
    id: '12890',
    createdAt: '2026-06-08',
    totalCostVnd: 248_200,
    paidVnd: 248_200,
    packageCount: 1,
    status: 'readyToShip',
    productName: 'Áo thun nam cotton basic',
    productQuantity: 2,
    supplierName: 'BasicWear Store',
    note: 'Size L, màu trắng',
    insurance: false,
    woodPacking: false,
    products: [
      {
        id: 'op-3',
        name: 'Áo thun nam cotton basic',
        variant: 'Màu: Trắng | Size: L',
        priceCny: 34,
        quantity: 2,
      },
    ],
    costs: {
      goodsVnd: 248_200,
      estimatedFeeVnd: 0,
      depositVnd: 74_460,
      totalVnd: 248_200,
      paidVnd: 248_200,
      remainingVnd: 0,
    },
  },
  '12811': {
    id: '12811',
    createdAt: '2026-06-01',
    totalCostVnd: 1_207_500,
    paidVnd: 362_250,
    packageCount: 3,
    status: 'processing',
    productName: 'Máy xay sinh tố đa năng',
    productQuantity: 1,
    supplierName: 'KitchenPro Vietnam',
    note: 'Kiểm tra kỹ trước khi giao',
    insurance: true,
    woodPacking: true,
    products: [
      {
        id: 'op-4',
        name: 'Máy xay sinh tố đa năng',
        variant: 'Công suất 1200W | Màu bạc',
        priceCny: 330,
        quantity: 1,
      },
    ],
    costs: {
      goodsVnd: 1_204_500,
      estimatedFeeVnd: 3_000,
      depositVnd: 362_250,
      totalVnd: 1_207_500,
      paidVnd: 362_250,
      remainingVnd: 845_250,
    },
  },
};
