import type { OrderStatusFilter } from '@/src/types/orders/orders.types';

export const ordersCopy = {
  title: 'Danh sách đơn hàng',
  filter: 'Lọc',
  filterTitle: 'Lọc đơn hàng',
  filterAll: 'Tất cả',
  orderNumberLabel: 'Mã đơn:',
  createdAtLabel: 'Ngày tạo:',
  totalCostLabel: 'Tổng chi phí:',
  paidLabel: 'Đã thanh toán:',
  packageCountLabel: 'Số sản phẩm:',
  customerLabel: 'Khách hàng:',
  shopLabel: 'Cửa hàng:',
  actions: 'Thao tác',
  deleteOrder: 'Xoá đơn',
  viewDetail: 'Xem chi tiết',
  editOrder: 'Sửa đơn',
  payOrder: 'Thanh toán',
  cancelOrder: 'Huỷ đơn',
  searchPlaceholder: 'Tìm khách hàng (tên, SĐT)...',
  searchClearA11y: 'Xóa tìm kiếm',
  searchCustomerHint: 'Nhập ít nhất 2 ký tự để tìm khách hàng',
  searchCustomerEmpty: 'Không tìm thấy khách hàng',
  searchCustomerError: 'Không thể tìm khách hàng',
  selectedCustomerLabel: 'Khách:',
  clearSelectedCustomerA11y: 'Xóa khách đã chọn',
  emptyOrders: 'Chưa có đơn hàng nào',
  emptyFilteredOrders: 'Không có đơn phù hợp bộ lọc',
  emptyCustomerSearchOrders: 'Khách hàng này chưa có đơn hàng',
  loadError: 'Không thể tải danh sách đơn hàng',
  retry: 'Thử lại',
  loadingOrders: 'Đang tải đơn hàng...',
  loadingMoreOrders: 'Đang tải thêm...',
  cancelModalTitle: 'Huỷ đơn hàng',
  cancelModalSubtitle: 'Nhập lý do huỷ cho đơn',
  cancelReasonLabel: 'Lý do huỷ',
  cancelReasonPlaceholder: 'Nhập lý do huỷ đơn',
  cancelReasonRequired: 'Vui lòng nhập lý do huỷ',
  cancelConfirm: 'Xác nhận huỷ',
  cancelDismiss: 'Đóng',
  cancelSuccess: 'Đã huỷ đơn hàng thành công',
  editModalTitle: 'Sửa đơn hàng',
  editModalSubtitle: 'Mã đơn:',
  editNoteLabel: 'Ghi chú',
  editNotePlaceholder: 'Nhập ghi chú đơn hàng...',
  editDismiss: 'Huỷ',
  editSave: 'Lưu thay đổi',
  editSuccess: 'Đã cập nhật đơn hàng',
} as const;

export const orderDetailCopy = {
  screenTitle: 'Chi tiết đơn hàng',
  back: 'Quay lại',
  notFound: 'Không tìm thấy đơn hàng',
  loading: 'Đang tải chi tiết đơn hàng...',
  loadError: 'Không thể tải chi tiết đơn hàng',
  retry: 'Thử lại',
  orderDateLabel: 'Ngày đặt:',
  paymentStatusLabel: 'Thanh toán:',
  paymentMethodLabel: 'Phương thức:',
  shopLabel: 'Cửa hàng:',
  customerLabel: 'Khách hàng:',
  customerPhoneLabel: 'SĐT:',
  customerAddressLabel: 'Địa chỉ:',
  warehouseLabel: 'Kho đóng gói:',
  packingOrderLabel: 'Phiếu đóng gói:',
  creatorLabel: 'Người tạo:',
  productsTitle: 'Sản phẩm',
  shippingTitle: 'Giao hàng',
  recipientLabel: 'Người nhận:',
  shippingPartnerLabel: 'Đơn vị vận chuyển:',
  trackingNumberLabel: 'Mã vận đơn:',
  shippingPayerLabel: 'Người trả phí ship:',
  codLabel: 'Thu COD:',
  noteTitle: 'Ghi chú',
  issueTitle: 'Vấn đề đơn hàng',
  costTitle: 'Chi phí',
  goodsAmount: 'Tiền hàng:',
  discountAmount: 'Giảm giá:',
  taxAmount: 'Thuế:',
  shippingFee: 'Phí vận chuyển:',
  totalAmount: 'Tổng tiền:',
  remainingAmount: 'Còn lại:',
  unitPriceLabel: 'Đơn giá:',
  lineTotalLabel: 'Thành tiền:',
  payOrder: 'Thanh toán',
  cancelOrder: 'Huỷ đơn',
  editOrder: 'Sửa đơn',
  paySuccess: 'Thanh toán thành công (mock)',
  cancelSuccess: 'Đã huỷ đơn hàng thành công',
} as const;

export const saleOrderPaymentStatusLabels: Record<string, string> = {
  pending: 'Chờ thanh toán',
  partial_paid: 'Thanh toán một phần',
  paid: 'Đã thanh toán',
  voided: 'Đã huỷ',
  pending_refund: 'Chờ hoàn tiền',
  refunded: 'Đã hoàn tiền',
};

export const saleOrderPaymentMethodLabels: Record<string, string> = {
  cod: 'COD',
  cash: 'Tiền mặt',
  bank_transfer: 'Chuyển khoản',
  online: 'Thanh toán online',
};

export const saleOrderShippingPayerLabels: Record<string, string> = {
  buyer: 'Người mua',
  seller: 'Người bán',
};

export const saleOrderStatusLabels: Record<string, string> = {
  pending: 'Chờ xác nhận',
  confirmed: 'Đã xác nhận',
  packing: 'Đang đóng gói',
  shipping: 'Đang giao',
  ready_to_ship: 'Sẵn sàng giao',
  delivered: 'Đã giao',
  cancelled: 'Đã huỷ',
  transferring: 'Đang chuyển khoản',
  pending_transfer: 'Chờ chuyển khoản',
  transfer_failed: 'Chuyển khoản thất bại',
  returned: 'Đã hoàn',
  partially_returned: 'Hoàn một phần',
};

export const orderStatusFilterLabels: Record<OrderStatusFilter, string> = {
  all: 'Tất cả',
  pending: saleOrderStatusLabels.pending,
  confirmed: saleOrderStatusLabels.confirmed,
  packing: saleOrderStatusLabels.packing,
  shipping: saleOrderStatusLabels.shipping,
  delivered: saleOrderStatusLabels.delivered,
  cancelled: saleOrderStatusLabels.cancelled,
};

/** @deprecated Use saleOrderStatusLabels for API statuses. */
export const orderStatusLabels = saleOrderStatusLabels;
