/** Static copy for the profile tab. */
export const profileCopy = {
  greeting: 'Xin chào',
  accountSection: 'Quản lý tài khoản',
  personalInfo: 'Thông tin cá nhân',
  supportSection: 'Nhân viên chăm sóc',
  supportStaffName: 'Tomoni VN',
  supportPhone: '0844.713.555',
  hotline: 'Hotline hỗ trợ: 0844.713.555 - 0823.943.777',
  logout: 'Đăng xuất',
  fallbackName: 'Khách',
  notifications: 'Thông báo',
  openZalo: 'Mở Zalo',
  callSupport: 'Gọi điện',
  staffSection: 'Nhân viên',
  staffList: 'Danh sách nhân viên',
} as const;

export const staffCopy = {
  screenTitle: 'Danh sách nhân viên',
  totalLabel: 'Tổng nhân viên',
  empty: 'Chưa có nhân viên',
  loadError: 'Không thể tải danh sách nhân viên',
  retry: 'Thử lại',
  noPhone: 'Chưa có số điện thoại',
  active: 'Đang hoạt động',
  inactive: 'Ngưng hoạt động',
} as const;

export const staffDetailCopy = {
  screenTitle: 'Chi tiết nhân viên',
  accountSection: 'Thông tin tài khoản',
  sellerSection: 'Nhà bán',
  actionsSection: 'Thao tác quản trị',
  emailLabel: 'Email',
  phoneLabel: 'Số điện thoại',
  roleLabel: 'Vai trò',
  statusLabel: 'Trạng thái',
  emailVerifiedLabel: 'Xác thực email',
  emailVerified: 'Đã xác thực',
  emailUnverified: 'Chưa xác thực',
  lastLoginLabel: 'Đăng nhập gần nhất',
  createdAtLabel: 'Ngày tạo',
  updatedAtLabel: 'Cập nhật lần cuối',
  sellerNameLabel: 'Tên nhà bán',
  sellerPhoneLabel: 'SĐT nhà bán',
  warehouseCountLabel: 'Số kho được gán',
  neverLoggedIn: 'Chưa đăng nhập',
  noSeller: '—',
  editInfo: 'Sửa thông tin',
  changePassword: 'Đổi mật khẩu',
  deactivate: 'Vô hiệu hoá',
  activate: 'Kích hoạt lại',
  deleteAccount: 'Xoá tài khoản',
  loadError: 'Không thể tải thông tin nhân viên',
  retry: 'Thử lại',
  editModalTitle: 'Sửa thông tin nhân viên',
  editSave: 'Lưu thay đổi',
  editDismiss: 'Huỷ',
  editSuccess: 'Đã cập nhật thông tin nhân viên',
  fullNameLabel: 'Họ và tên',
  nameRequired: 'Vui lòng nhập họ và tên',
  emailRequired: 'Vui lòng nhập email',
  emailInvalid: 'Email không hợp lệ',
  roleStaff: 'Nhân viên',
  roleAdmin: 'Quản trị viên',
  changePasswordTitle: 'Đổi mật khẩu',
  changePasswordHint:
    'Người dùng sẽ cần đăng nhập lại bằng mật khẩu mới ở lần tiếp theo.',
  adminCurrentPasswordLabel: 'Mật khẩu hiện tại của bạn',
  newPasswordLabel: 'Mật khẩu mới',
  confirmPasswordLabel: 'Xác nhận mật khẩu mới',
  changePasswordSubmit: 'Cập nhật mật khẩu',
  changePasswordSuccess: 'Đã đổi mật khẩu thành công',
  currentPasswordRequired: 'Vui lòng nhập mật khẩu hiện tại',
  newPasswordRequired: 'Vui lòng nhập mật khẩu mới',
  newPasswordTooShort: 'Mật khẩu mới phải có ít nhất 8 ký tự',
  confirmPasswordRequired: 'Vui lòng xác nhận mật khẩu mới',
  confirmPasswordMismatch: 'Mật khẩu xác nhận không khớp',
  deactivateConfirmTitle: 'Vô hiệu hoá người dùng',
  deactivateConfirmMessage:
    'Người dùng sẽ không thể đăng nhập cho đến khi được kích hoạt lại.',
  activateConfirmTitle: 'Kích hoạt người dùng',
  activateConfirmMessage: 'Người dùng sẽ có thể đăng nhập lại.',
  deactivateSuccess: 'Đã vô hiệu hoá người dùng',
  activateSuccess: 'Đã kích hoạt người dùng',
  deleteConfirmTitle: 'Xoá tài khoản',
  deleteConfirmMessage:
    'Hành động này không thể hoàn tác. Bạn có chắc muốn xoá tài khoản này?',
  deleteSuccess: 'Đã xoá tài khoản',
  confirm: 'Xác nhận',
  cancel: 'Huỷ',
} as const;

export const staffPasswordRules = {
  minLength: 8,
} as const;

export const personalInfoCopy = {
  screenTitle: 'Thông tin cá nhân',
  back: 'Quay lại',
  avatarHint: 'Ảnh đại diện',
  changeAvatar: 'Thay đổi ảnh',
  fullNameLabel: 'Họ và tên',
  fullNamePlaceholder: 'Nhập họ và tên',
  usernameLabel: 'Tên đăng nhập',
  emailLabel: 'Email',
  emailPlaceholder: 'Nhập email',
  phoneLabel: 'Số điện thoại',
  phonePlaceholder: 'Nhập số điện thoại',
  addressLabel: 'Địa chỉ nhận hàng',
  addressPlaceholder: 'Nhập địa chỉ nhận hàng',
  save: 'Lưu thông tin',
  saveSuccess: 'Đã cập nhật thông tin cá nhân',
  fullNameRequired: 'Vui lòng nhập họ và tên',
  emailInvalid: 'Email không hợp lệ',
  phoneInvalid: 'Số điện thoại không hợp lệ',
  addressRequired: 'Vui lòng nhập địa chỉ nhận hàng',
} as const;

/** Default empty profile before user data is loaded. */
export const emptyUserProfile = {
  fullName: '',
  username: '',
  email: '',
  phone: '',
  address: '',
} as const;

export const profileSupportLinks = {
  zaloPhone: '0844713555',
  hotlinePrimary: '0844713555',
  hotlineSecondary: '0823943777',
} as const;
