/** Copy and options for seller product management in the profile tab. */

export const productsCopy = {
  sectionTitle: 'Sản phẩm',
  productList: 'Danh sách sản phẩm',
  createProduct: 'Tạo sản phẩm',
  listScreenTitle: 'Danh sách sản phẩm',
  createScreenTitle: 'Tạo sản phẩm',
  totalLabel: 'Tổng sản phẩm',
  empty: 'Chưa có sản phẩm',
  loadError: 'Không thể tải danh sách sản phẩm',
  retry: 'Thử lại',
  active: 'Đang bán',
  inactive: 'Ngưng bán',
  createSuccess: 'Đã tạo sản phẩm thành công',
  createError: 'Không thể tạo sản phẩm',
  editScreenTitle: 'Sửa sản phẩm',
  editSuccess: 'Đã cập nhật sản phẩm',
  editError: 'Không thể cập nhật sản phẩm',
  editLoadError: 'Không thể tải thông tin sản phẩm',
  editSave: 'Lưu thay đổi',
  editSaving: 'Đang lưu…',
  deleteProduct: 'Xóa sản phẩm',
  deleteConfirmTitle: 'Xóa sản phẩm?',
  deleteConfirmMessage:
    'Hành động này không thể hoàn tác. Sản phẩm sẽ bị xóa khỏi danh mục.',
  deleteSuccess: 'Đã xóa sản phẩm',
  deleteError: 'Không thể xóa sản phẩm',
  detailActionsSection: 'Thao tác',
  detailEditProduct: 'Sửa sản phẩm',
  listEditAction: 'Sửa',
  listDeleteAction: 'Xóa',
  editComboReadOnlyHint:
    'Thành phần combo không thể chỉnh trên mobile — hãy dùng web nếu cần thay đổi.',
  save: 'Tạo mới',
  cancel: 'Huỷ',
  basicSection: 'Thông tin cơ bản',
  dimensionsSection: 'Kích thước và trọng lượng',
  statusSection: 'Hình ảnh & trạng thái',
  skuLabel: 'Mã SKU',
  skuPlaceholder: 'VD: 4513574014152',
  skuHint: 'Mã sản phẩm duy nhất',
  nameLabel: 'Tên sản phẩm',
  namePlaceholder: 'Tên hiển thị',
  barcodeLabel: 'Mã vạch',
  barcodePlaceholder: 'Tùy chọn',
  barcodeHint: 'Định dạng EAN-8, EAN-13, hoặc UPC (8–13 chữ số)',
  priceLabel: 'Giá',
  priceHint: 'Giá cơ bản để tính toán',
  unitLabel: 'Đơn vị',
  unitHint: 'Đơn vị dùng cho tồn kho, đơn hàng và thanh toán',
  unitPickerTitle: 'Chọn đơn vị',
  minStockLabel: 'Tồn tối thiểu',
  minStockHint: 'Cảnh báo khi tồn kho dưới mức này',
  descriptionLabel: 'Mô tả',
  descriptionPlaceholder: 'Tùy chọn',
  weightLabel: 'Trọng lượng (g)',
  lengthLabel: 'Chiều dài (cm)',
  widthLabel: 'Chiều rộng (cm)',
  heightLabel: 'Chiều cao (cm)',
  imageUrlLabel: 'URL hình ảnh',
  imageUrlPlaceholder: 'https://…',
  imageUrlHint: 'Dán URL công khai của ảnh sản phẩm (tùy chọn)',
  productImageLabel: 'Ảnh sản phẩm',
  pickFromLibrary: 'Thư viện ảnh',
  pickFromCamera: 'Chụp ảnh',
  removeImage: 'Gỡ ảnh',
  productImageHint: 'Chụp ảnh bằng camera hoặc chọn từ thư viện — ảnh sẽ upload khi tạo sản phẩm',
  productImageHintEdit:
    'Chọn ảnh mới bằng camera hoặc thư viện — ảnh sẽ cập nhật khi bạn lưu',
  removeNewImage: 'Hủy ảnh mới',
  productImageHintSimulator:
    'Trên Simulator iOS, camera không khả dụng — hãy dùng "Thư viện ảnh" (kéo ảnh vào Simulator) hoặc test trên thiết bị thật.',
  cameraPermissionDenied: 'Ứng dụng cần quyền truy cập camera',
  imagePickerError: 'Không thể mở thư viện ảnh',
  cameraError: 'Không thể mở camera',
  simulatorCameraUnavailable:
    'Camera không khả dụng trên Simulator iOS. Vui lòng chọn "Thư viện ảnh" hoặc test trên thiết bị thật.',
  isActiveLabel: 'Đang hoạt động',
  isActiveHint: 'Hiển thị và bán sản phẩm này',
  isComboLabel: 'Sản phẩm combo',
  isComboHint: 'Bật nếu sản phẩm gồm nhiều thành phần',
  comboItemsSection: 'Thành phần combo',
  comboSelectIngredientHeader: 'Chọn nguyên liệu',
  comboQuantityPerComboHeader: 'SL/combo',
  comboSelectProduct: 'Chọn sản phẩm',
  comboItemsHint: 'Chọn sản phẩm và số lượng cho từng thành phần trong combo',
  comboItemsEmpty: 'Chưa thêm sản phẩm nào',
  comboItemsRequired: 'Combo cần ít nhất một sản phẩm thành phần',
  addComboItem: 'Thêm dòng',
  removeComboItem: 'Gỡ',
  comboItemQuantityLabel: 'Số lượng',
  comboPickerTitle: 'Chọn sản phẩm thành phần',
  comboPickerSearchPlaceholder: 'Tìm theo tên hoặc SKU',
  comboPickerEmpty: 'Không có sản phẩm khả dụng',
  comboPickerAlreadyAdded: 'Đã thêm',
  comboItemAlreadyAdded: 'Sản phẩm đã có trong combo',
  comboModalTitle: 'Thành phần combo',
  comboModalDone: 'Xong',
  comboModalClose: 'Đóng',
  comboConfigureButton: 'Thiết lập thành phần',
  comboSummaryEmpty: 'Chưa có thành phần',
  comboSummaryCount: (count: number) =>
    `${count} thành phần đã chọn`,
  skuRequired: 'Vui lòng nhập mã SKU',
  nameRequired: 'Vui lòng nhập tên sản phẩm',
  priceInvalid: 'Giá không hợp lệ',
  sellerRequired: 'Tài khoản không gắn nhà bán — không thể tạo sản phẩm',
  detailScreenTitle: 'Chi tiết sản phẩm',
  detailLoadError: 'Không thể tải chi tiết sản phẩm',
  detailNotFound: 'Không tìm thấy sản phẩm',
  detailStockSection: 'Tồn kho',
  detailAvailableStockLabel: 'Khả dụng',
  detailReservedStockLabel: 'Giữ chỗ',
  detailTotalStockLabel: 'Tổng tồn',
  detailMinStockLabel: 'Tồn tối thiểu',
  detailStatusSection: 'Trạng thái',
  detailStatusLabel: 'Trạng thái bán',
  detailDimensionsSection: 'Kích thước & khối lượng',
  detailWeightLabel: 'Khối lượng',
  detailDimensionsLabel: 'Kích thước',
  detailUnitLabel: 'Đơn vị',
  detailBarcodeLabel: 'Mã vạch',
  detailDescriptionSection: 'Mô tả sản phẩm',
  detailNoDescription: 'Chưa có mô tả sản phẩm',
  detailSellerSection: 'Người bán',
  detailEmptyValue: '—',
  detailBasicSection: 'Thông tin sản phẩm',
  detailIdLabel: 'ID',
  detailUuidLabel: 'UUID',
  detailSellerIdLabel: 'Seller ID',
  detailNameLabel: 'Tên sản phẩm',
  detailPriceLabel: 'Giá',
  detailPriceRawLabel: 'Giá (API)',
  detailIsComboLabel: 'Loại sản phẩm',
  detailCombo: 'Combo',
  detailSimple: 'Sản phẩm thường',
  detailIsInStockLabel: 'Còn hàng',
  detailIsLowStockLabel: 'Sắp hết',
  detailIsBelowMinStockLabel: 'Dưới tồn tối thiểu',
  detailIsOutOfStockLabel: 'Hết hàng',
  detailWarehousesCountLabel: 'Số kho',
  detailImagesSection: 'Hình ảnh',
  detailImageUrlLabel: 'URL ảnh gốc',
  detailThumbnailUrlLabel: 'URL thumbnail',
  detailPrimaryImageLabel: 'Ảnh chính',
  detailGalleryLabel: 'Thư viện ảnh',
  detailNoImages: 'Không có ảnh trong thư viện',
  detailRecipeSection: 'Thành phần combo',
  detailNoRecipeItems: 'Không có thành phần',
  detailRecipeQuantityLabel: 'Số lượng',
  detailRecipeComponentLabel: 'Thành phần',
  detailTimestampsSection: 'Thời gian',
  detailCreatedAtLabel: 'Ngày tạo',
  detailUpdatedAtLabel: 'Cập nhật lần cuối',
  detailSellerIdFieldLabel: 'ID nhà bán',
  detailSellerUuidLabel: 'UUID nhà bán',
  detailSellerCodeLabel: 'Mã nhà bán',
  detailSellerNameLabel: 'Tên nhà bán',
  detailSellerEmailLabel: 'Email',
  detailSellerPhoneLabel: 'Số điện thoại',
  detailSellerAddressLabel: 'Địa chỉ',
  detailSellerTaxLabel: 'Mã số thuế',
  detailSellerStatusLabel: 'Trạng thái nhà bán',
  detailYes: 'Có',
  detailNo: 'Không',
  detailLengthLabel: 'Chiều dài',
  detailWidthLabel: 'Chiều rộng',
  detailHeightLabel: 'Chiều cao',
  detailVolumetricWeightLabel: 'Khối lượng quy đổi',
  detailImagePrimaryBadge: 'Ảnh chính',
  detailImageSortLabel: 'Thứ tự',
} as const;

export type ProductUnitValue =
  | 'piece'
  | 'gram'
  | 'kilogram'
  | 'milliliter'
  | 'liter'
  | 'box'
  | 'pack'
  | 'carton'
  | 'meter'
  | 'centimeter'
  | 'square_meter';

export const PRODUCT_UNIT_OPTIONS: {
  value: ProductUnitValue;
  label: string;
}[] = [
  { value: 'piece', label: 'Cái' },
  { value: 'gram', label: 'Gram' },
  { value: 'kilogram', label: 'Kilogram' },
  { value: 'milliliter', label: 'Mililit' },
  { value: 'liter', label: 'Lít' },
  { value: 'box', label: 'Hộp/Thùng' },
  { value: 'pack', label: 'Gói' },
  { value: 'carton', label: 'Thùng Carton' },
  { value: 'meter', label: 'Mét' },
  { value: 'centimeter', label: 'Centimet' },
  { value: 'square_meter', label: 'Mét Vuông' },
];

export const productsPageSize = 20;

/** Upload ảnh sản phẩm có thể mất lâu hơn request JSON thông thường. */
export const productCreateUploadTimeoutMs = 120_000;
