/** Copy and limits for the create-order draft product list. */
export const draftCopy = {
  title: 'Tạo đơn hàng',
  productsSection: 'Sản phẩm',
  addProductAction: 'Thêm Sản Phẩm',
  quantityLabel: 'Số lượng',
  unitPriceFieldLabel: 'Đơn giá',
  discountLabel: 'Giảm giá',
  lineTotalFieldLabel: 'Tổng',
  totalGoodsLabel: 'Tổng tiền hàng:',
  addProduct: 'Thêm sản phẩm',
  createOrder: 'Tạo đơn hàng',
  supplierPrefix: 'Nhà cung cấp:',
  insurance: 'Bảo hiểm',
  woodPacking: 'Đóng gỗ',
  unitPriceLabel: 'Đơn giá:',
  lineTotalLabel: 'Thành tiền:',
  goodsAmount: 'Tiền hàng:',
  estimatedFee: 'Phí tạm tính:',
  deposit: 'Đặt cọc:',
  totalAmount: 'Tổng tiền:',
  notePlaceholder: 'Nhập ghi chú cho đơn hàng',
  deleteShop: 'Xoá Shop',
  decreaseQuantity: 'Giảm số lượng',
  increaseQuantity: 'Tăng số lượng',
  removeProduct: 'Xoá sản phẩm',
  emptyDraft: 'Chưa có sản phẩm. Bấm "Thêm Sản Phẩm" để bắt đầu.',
  addProductRequiresWarehouse:
    'Vui lòng chọn kho đóng gói ở phần trên trước khi thêm sản phẩm.',
  defaultVariant: 'Mặc định',
  defaultSupplier: 'Tosol',
  outOfStockError: 'Sản phẩm đã hết hàng',
  exceedsStock: 'Chỉ còn {max} sản phẩm trong kho',
  exceedsStockInDraft:
    'Bạn đã có sản phẩm này trong đơn. Tối đa {max} sản phẩm',
  priceOnRequest: 'Liên hệ',
  taxRateLabel: 'Thuế suất (%)',
  customPriceRequired: 'Vui lòng nhập đơn giá cho sản phẩm "{name}".',
  customPricePlaceholder: 'Nhập đơn giá',
  taxRatePlaceholder: '0',
  noProductsToSubmit: 'Vui lòng thêm ít nhất một sản phẩm trước khi tạo đơn.',
  draftListEmpty: 'Chưa có đơn hàng nào được tạo',
  draftListEmptyHint: 'Bấm "Tạo đơn mới" để bắt đầu lên đơn hàng.',
  draftListNewOrder: 'Đơn hàng mới',
  draftListItemTitle: 'Đơn nháp',
  draftListProductCountLabel: 'sản phẩm',
  draftListEmptyProducts: 'Chưa có sản phẩm',
  createNewDraft: 'Tạo đơn mới',
  continueDraft: 'Tiếp tục tạo đơn',
  deleteDraft: 'Xoá đơn nháp',
  deleteDraftConfirm: 'Bạn có chắc muốn xoá đơn nháp này?',
  deleteDraftCancel: 'Huỷ',
  deleteDraftConfirmAction: 'Xoá',
  deleteAllDrafts: 'Xoá tất cả',
  deleteAllDraftsConfirm: 'Bạn có chắc muốn xoá tất cả đơn nháp?',
  addProductSheetTitle: 'Thêm sản phẩm',
  addProductSheetSearchPlaceholder: 'Tìm theo tên hoặc SKU...',
  addProductSheetStagedSection: 'Đã chọn',
  addProductSheetEmpty: 'Không tìm thấy sản phẩm',
  addProductSheetDone: 'Hoàn thành',
  addProductSheetCancel: 'Huỷ',
  addProductSheetRecentProducts: 'Sản phẩm gần đây',
  addProductSheetSuggestions: 'Gợi ý',
  addProductSheetSellerRequired: 'Không thể tải sản phẩm. Vui lòng đăng nhập lại.',
  addProductSheetContextRequired: 'Vui lòng chọn kho đóng gói trước khi thêm sản phẩm.',
  addProductSheetCommitError: 'Không thể thêm sản phẩm',
} as const;

export const draftQuantityLimits = {
  min: 1,
  max: 99,
} as const;

export const draftTaxRateLimits = {
  min: 0,
  max: 100,
} as const;

/** Ghi AsyncStorage sau khi ngừng chỉnh sửa draft (ms). */
export const draftPersistDebounceMs = 800;
